GEMINI_API_KEY = "AIzaSyDi7omR9--Br3bNCAkMBCYcH42BUcQzFLg"
QDRANT_URL = "https://84159d48-6f94-4409-982d-5210244d7831.europe-west3-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.rNqc84TGVW4yTiO8tnEFrs3HrZdQ3Fv1F7EpxcyjzLA"
